version: '3.9'

services:
 
  # Harmony Service - Main instance
  harmony_service:
    image: ehitelrc/harmony_service:latest
    container_name: harmony_service
    ports:
      - '8098:8098'
    restart: unless-stopped
    env_file:
      - .env

  # Harmony Service - Messages In instance
  harmony_service_messages_in:
    image: ehitelrc/harmony_service:latest
    container_name: harmony_service_messages_in
    ports:
      - '8099:8098'
    restart: unless-stopped
    env_file:
      - .env

  # Web apllication
  harmony_web:
    image: ehitelrc/harmony_web:latest
    container_name: harmony_web
    ports:
      - '80:80'
    restart: unless-stopped